// vue/vue-sample/src/components/Menubar.vue
<template>
    <div class="menu">
        <nav
            class="flex items-center justify-between flex-wrap bg-white py-4 lg:px-12 shadow border-solid border-t-2 border-blue-700">
            <div class="flex justify-between lg:w-auto w-full lg:border-b-0 pl-6 pr-2 border-solid border-b-2 border-gray-300 pb-5 lg:pb-0">
                <div class="flex items-center flex-shrink-0 text-gray-800 mr-16">
                    <span class="font-semibold text-xl tracking-tight">HOME</span>
                </div>
                <div class="block lg:hidden ">
                    <button
                        id="nav"
                        class="flex items-center px-3 py-2 border-2 rounded text-blue-700 border-blue-700 hover:text-blue-700 hover:border-blue-700">
                        <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title>
                            <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
                        </svg>
                    </button>
                </div>
            </div>
        
            <div class="menu w-full lg:block flex-grow lg:flex lg:items-center lg:w-auto lg:px-3 px-8">
                <div class="text-md font-bold text-blue-700 lg:flex-grow">
                    <a href="#responsive-header"
                    class="block mt-4 lg:inline-block lg:mt-0 hover:text-white px-4 py-2 rounded hover:bg-blue-700 mr-2">
                        Menu 1
                    </a>
                    <a href="#responsive-header"
                    class=" block mt-4 lg:inline-block lg:mt-0 hover:text-white px-4 py-2 rounded hover:bg-blue-700 mr-2">
                        Menu 2
                    </a>
                    <a href="#responsive-header"
                    class="block mt-4 lg:inline-block lg:mt-0 hover:text-white px-4 py-2 rounded hover:bg-blue-700 mr-2">
                        Menu 3
                    </a>
                </div>
                <!-- This is an example component -->
                <div class="relative mx-auto text-gray-600 lg:block hidden">
                    <input
                        class="border-2 border-gray-300 bg-white h-10 pl-2 pr-8 rounded-lg text-sm focus:outline-none"
                        type="search" name="search" placeholder="Search">
                    <button type="submit" class="absolute right-0 top-0 mt-3 mr-2">
                        <svg class="text-gray-600 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
                            version="1.1" id="Capa_1" x="0px" y="0px"
                            viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;"
                            xml:space="preserve"
                            width="512px" height="512px">
                    <path
                        d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z"/>
                </svg>
                    </button>
                </div>
                <div class="flex ">
                    <a href="#"
                    class="block text-md px-4 py-2 rounded text-blue-700 ml-2 font-bold hover:text-white mt-4 hover:bg-blue-700 lg:mt-0">Sign
                        in</a>
        
                    <a href="#"
                    class=" block text-md px-4  ml-2 py-2 rounded text-blue-700 font-bold hover:text-white mt-4 hover:bg-blue-700 lg:mt-0">login</a>
                </div>
            </div>
        </nav>
    </div>
</template>

// nest/community/frontend/components/Menubar.tsx
import React, { useCallback } from 'react';
import { client } from '../api/defaultClient';

const Menubar = () => { 
    const loginClickListener = useCallback(() => {
        window.location.href = 'http://localhost:3065/api/auth/google';
    }, [])

    const isExtendedLogin = useCallback(() => {
        client.get('/auth/refresh');
    }, [])

    const clickAccessListener = useCallback(() => {
        client.get('/auth')
            .then((res) => console.log(res.data))
            .catch((err) => console.error(err));
    }, [])
    
    return (
        <nav className=" bg-white w-full flex relative justify-between items-center mx-auto px-8 h-20">
            <div className="inline-flex">
                <a className="_o6689fn" href="/">
                    Home
                </a>
            </div>
            <div className="hidden sm:block flex-shrink flex-grow-0 justify-start px-2">
                <div className="inline-block">
                    <div className="inline-flex items-center max-w-full">
                        <button className="flex items-center flex-grow-0 flex-shrink pl-2 relative w-60 border rounded-full px-1  py-1" type="button">
                            <div className="block flex-grow flex-shrink overflow-hidden">Start your search</div>
                            <div className="flex items-center justify-center relative  h-8 w-8 rounded-full">
                                <svg
                                    viewBox="0 0 32 32"
                                    xmlns="http://www.w3.org/2000/svg"
                                    aria-hidden="true"
                                    role="presentation"
                                    focusable="false"
                                    style={{ display: "block", fill: "none", width: "12px", height: "12px", stroke: "currentcolor", strokeWidth: "5.33333", overflow: "visible" }}
                                >
                                    <g fill="none">
                                        <path
                                            d="m13 24c6.0751322 0 11-4.9248678 11-11 0-6.07513225-4.9248678-11-11-11-6.07513225 0-11 4.92486775-11 11 0 6.0751322 4.92486775 11 11 11zm8-3 9 9"
                                        ></path>
                                    </g>
                                </svg>
                            </div>
                        </button>
                    </div>
                </div>
            </div>
            <div className="flex-initial">
            <div className="flex justify-end items-center relative">    

                <div className="block">
                    <div onClick={ clickAccessListener } style={{ cursor: "pointer" }}>access</div>
                    <div onClick={ isExtendedLogin } style={{ cursor: "pointer" }}>연장</div>
                    { true ? <div onClick={ loginClickListener} style={{ cursor: "pointer" }}>Login</div> : <div className="inline relative">
                        <button type="button" className="inline-flex items-center relative px-2 border rounded-full hover:shadow-lg">
                            <div className="pl-1">
                                <svg
                                    viewBox="0 0 32 32"
                                    xmlns="http://www.w3.org/2000/svg"
                                    aria-hidden="true"
                                    role="presentation"
                                    focusable="false"
                                    style={{ display: "block", fill: "none", height: "16px", width: "16px", stroke: "currentcolor", strokeWidth: "3", overflow: "visible" }}
                                >
                                    <g fill="none" fill-rule="nonzero">
                                        <path d="m2 16h28"></path>
                                        <path d="m2 24h28"></path>
                                        <path d="m2 8h28"></path>
                                    </g>
                                </svg>
                            </div>

                            <div className="block flex-grow-0 flex-shrink-0 h-10 w-12 pl-5">
                                <svg
                                    viewBox="0 0 32 32"
                                    xmlns="http://www.w3.org/2000/svg"
                                    aria-hidden="true"
                                    role="presentation"
                                    focusable="false"
                                    style={{ display: "block", height: "100%", width: "100%", fill: "currentcolor" }}
                                >
                                    <path d="m16 .7c-8.437 0-15.3 6.863-15.3 15.3s6.863 15.3 15.3 15.3 15.3-6.863 15.3-15.3-6.863-15.3-15.3-15.3zm0 28c-4.021 0-7.605-1.884-9.933-4.81a12.425 12.425 0 0 1 6.451-4.4 6.507 6.507 0 0 1 -3.018-5.49c0-3.584 2.916-6.5 6.5-6.5s6.5 2.916 6.5 6.5a6.513 6.513 0 0 1 -3.019 5.491 12.42 12.42 0 0 1 6.452 4.4c-2.328 2.925-5.912 4.809-9.933 4.809z"></path>
                                </svg>
                            </div>
                        </button>
                    </div>}
                </div>
            </div>
            </div>
        </nav>
    )
}

export default Menubar;
